//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IUnit 
{
	NoiseQuencher InflowNoiseQuencher { get;set; }

	NoiseQuencher ExtractNoiseQuencher { get;set; }

	IFan Fan { get;set; }

	IHeater Heater { get;set; }

	ICooler Cooler { get;set; }

	FilterType Filter { get;set; }

}

